development:
  allow_member_record_edits: true
  allow_self_signup: true
  base_url: localhost:3000
  email:
    from_name: Jim's App
    from_email: mrhistory@gmail.com
    welcome_subject: Welcome to Jim's App - Members
    forgot_password_subject: Your new password

test:
  allow_member_record_edits: true
  allow_self_signup: true
  base_url: localhost:3000
  email:
    from_name: Jim's App
    from_email: mrhistory@gmail.com
    welcome_subject: Welcome to Jim's App - Members
    forgot_password_subject: Your new password

production:
  allow_member_record_edits: true
  allow_self_signup: true
  base_url: members-dev.herokuapp.com
  email:
    from_name: Jim's App
    from_email: mrhistory@gmail.com
    welcome_subject: Welcome to Jim's App - Members
    forgot_password_subject: Your new password