development:
  allow_member_record_edits: true
  allow_self_signup: true
  base_url: localhost:3000
  email:
    from_name: '1Voice'
    from_email: 'mrhistory@gmail.com'
    welcome_subject: 'Welcome to 1Voice - Members'

test:
  allow_member_record_edits: true
  allow_self_signup: true
  base_url: localhost:3000
  email:
    from_name: '1Voice'
    from_email: 'mrhistory@gmail.com'
    welcome_subject: 'Welcome to 1Voice - Members'

production:
  allow_member_record_edits: true
  allow_self_signup: true
  base_url: localhost:3000
  email:
    from_name: '1Voice'
    from_email: 'mrhistory@gmail.com'
    welcome_subject: 'Welcome to 1Voice - Members'